// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmI9AYkZwFLQHxWumN81cfhh1odsivmnA',
    appId: '1:225840976436:web:15b656495b6ffc51127061',
    messagingSenderId: '225840976436',
    projectId: 'flutterfire-ui-codelab-149ea',
    authDomain: 'flutterfire-ui-codelab-149ea.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-149ea.appspot.com',
    measurementId: 'G-L7V9G5WSSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOHufVHVP99ukDRylSaED9drYTDOTGqdw',
    appId: '1:225840976436:android:73b46ed7188ce3ee127061',
    messagingSenderId: '225840976436',
    projectId: 'flutterfire-ui-codelab-149ea',
    storageBucket: 'flutterfire-ui-codelab-149ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY1cMPGXEykjAVdNf0wEXJ4D9gsyyTzbc',
    appId: '1:225840976436:ios:aca73536ecc22e51127061',
    messagingSenderId: '225840976436',
    projectId: 'flutterfire-ui-codelab-149ea',
    storageBucket: 'flutterfire-ui-codelab-149ea.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY1cMPGXEykjAVdNf0wEXJ4D9gsyyTzbc',
    appId: '1:225840976436:ios:aca73536ecc22e51127061',
    messagingSenderId: '225840976436',
    projectId: 'flutterfire-ui-codelab-149ea',
    storageBucket: 'flutterfire-ui-codelab-149ea.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmI9AYkZwFLQHxWumN81cfhh1odsivmnA',
    appId: '1:225840976436:web:c3c6e0a4fbff83d1127061',
    messagingSenderId: '225840976436',
    projectId: 'flutterfire-ui-codelab-149ea',
    authDomain: 'flutterfire-ui-codelab-149ea.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-149ea.appspot.com',
    measurementId: 'G-14SWKCT5XX',
  );
}
